// Die 20 bevölkerungsreichsten Länder je Kontinent (nach Einwohnerzahl ausgewählt,
// innerhalb der Gruppe alphabetisch sortiert). Kontinente mit weniger als 20
// souveränen Staaten (Südamerika, Ozeanien) enthalten alle ihre Staaten.
// Vatikanstadt sowie nicht bzw. nur teilweise anerkannte Gebiete (z.B. Kosovo)
// bleiben ausgeschlossen. Transkontinentale Staaten sind der Region zugeordnet,
// in der sie üblicherweise geführt werden (Russland: Europa, Türkei: Asien).
export interface CountryGroup {
  continent: string;
  countries: string[];
}

export const COUNTRIES_BY_CONTINENT: CountryGroup[] = [
  {
    continent: "Europa",
    countries: [
      "Belarus",
      "Belgien",
      "Deutschland",
      "Frankreich",
      "Griechenland",
      "Großbritannien",
      "Italien",
      "Niederlande",
      "Österreich",
      "Polen",
      "Portugal",
      "Rumänien",
      "Russland",
      "Schweden",
      "Schweiz",
      "Serbien",
      "Spanien",
      "Tschechien",
      "Ukraine",
      "Ungarn",
    ],
  },
  {
    continent: "Asien",
    countries: [
      "Afghanistan",
      "Bangladesch",
      "China",
      "Indien",
      "Indonesien",
      "Irak",
      "Iran",
      "Japan",
      "Jemen",
      "Malaysia",
      "Myanmar",
      "Nepal",
      "Pakistan",
      "Philippinen",
      "Saudi-Arabien",
      "Südkorea",
      "Thailand",
      "Türkei",
      "Usbekistan",
      "Vietnam",
    ],
  },
  {
    continent: "Afrika",
    countries: [
      "Ägypten",
      "Algerien",
      "Angola",
      "Äthiopien",
      "Burkina Faso",
      "Demokratische Republik Kongo",
      "Elfenbeinküste",
      "Ghana",
      "Kamerun",
      "Kenia",
      "Madagaskar",
      "Mali",
      "Marokko",
      "Mosambik",
      "Niger",
      "Nigeria",
      "Sudan",
      "Südafrika",
      "Tansania",
      "Uganda",
    ],
  },
  {
    continent: "Nordamerika",
    countries: [
      "Bahamas",
      "Barbados",
      "Belize",
      "Costa Rica",
      "Dominikanische Republik",
      "El Salvador",
      "Grenada",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaika",
      "Kanada",
      "Kuba",
      "Mexiko",
      "Nicaragua",
      "Panama",
      "St. Lucia",
      "St. Vincent und die Grenadinen",
      "Trinidad und Tobago",
      "USA",
    ],
  },
  {
    continent: "Südamerika",
    countries: [
      "Argentinien",
      "Bolivien",
      "Brasilien",
      "Chile",
      "Ecuador",
      "Guyana",
      "Kolumbien",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    continent: "Ozeanien",
    countries: [
      "Australien",
      "Fidschi",
      "Kiribati",
      "Marshallinseln",
      "Mikronesien",
      "Nauru",
      "Neuseeland",
      "Palau",
      "Papua-Neuguinea",
      "Salomonen",
      "Samoa",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
    ],
  },
];
