FROM docker.io/library/node:22-alpine AS build
WORKDIR /build
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_API_URL=http://localhost:8081
ARG VITE_USER_APP_URL=http://localhost:8083
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_USER_APP_URL=$VITE_USER_APP_URL
RUN npm run build

FROM docker.io/nginxinc/nginx-unprivileged:1.27-alpine
COPY --from=build /build/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
